### ISSUE TITLE
Changes in CartFragment wouldnt stick !

### ISSUE THREAD

**Issue by sooorajjj** [sooorajjj/KOT#1]
c68241dd223d6ba3b2b02f21eb53029182951c7e this commit needs some more work i think
ie on adding the item to cart and in the cart when i press + button it wouldn't show the updated amount and quantity and then i go back to items its not there too .
But now in items fragment if i press add now the amount shown in items fragment looks different from whats in cart fragment.
It actually did add the amount in cart fragment earlier but it didn't get updatedin the TextView

> ```
>     tvTotalItems
>     tvTotalPrice
> ```

![2282718721818746599 3faccount_id 3d1](https://cloud.githubusercontent.com/assets/6510673/18303552/4cacd312-74fb-11e6-8d89-236f2d1c55dd.png)                ![794088382293038](https://cloud.githubusercontent.com/assets/6510673/18303571/67694e92-74fb-11e6-8f6b-f1001a862264.png)

i suspect the issue is here 
https://github.com/sooorajjj/KOT/blob/master/app/src/main/java/online/klok/kot/shopping_cart/CartFragment.java#L53-L73

**Comment by sooorajjj** [comment]
Ohk , pushed  a fix a6a73505856cf87fe0f1ce1d350035dbcda9b24d now the TextView's gets updated on btn_add press in CartFragment .

So whats left is , it still wouldn't  send the updated data back to ItemFragment view ... i mean the TextView's in the ItemFragment doesn't get updated with respect to Changes in CartFragment .

**Comment by sooorajjj** [comment]
sorry , I really don't need to sent the  send the updated data back to ItemFragment view thanks to @NileshJarad

**Comment by sooorajjj** [comment]
Actually i do need to store the data in POJO class (Plain Old Java Object)  so that if i press btn_less  it would actually store the new data and when i move back to ItemFragment it would actually show new updated amount and qty else .... the new changes made in ItemFragment would be replaced with the changes in CartFragment and that would show wrong amount in cart RecycleView

**Comment by NileshJarad** [comment]
For that we have to user some common place to store the data.
Like data base where we can store actual data and we can fetch data from common  place, Where we can update qty factor irrespective of screen . So we need to use Database now

**Comment by sooorajjj** [comment]
1205aa9b4ac4692110318dd1674aa8e8ff051c75 this commit fixed the issue @NileshJarad thanks m8
